# Generated by Django 5.2.11 on 2026-02-18 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("JUMBO", "Jumbo"),
                            ("COMPRESSOR", "Compresor"),
                            ("GENERATOR", "Generador"),
                            ("LOADER", "Cargador Frontal"),
                            ("TRUCK", "Camión"),
                            ("SCOOP", "Scoop"),
                            ("TELEHANDLER", "Telescópico"),
                            ("PICKUP", "Camioneta"),
                            ("DRILL", "Perforadora/Track drill"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("DETENIDO", "Detenido"),
                            ("MANTENCION", "Mantención"),
                            ("STANDBY", "Standby"),
                        ],
                        default="OPERATIVO",
                        max_length=30,
                    ),
                ),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="equipment_e_categor_458d69_idx",
                    ),
                    models.Index(
                        fields=["status"], name="equipment_e_status_fb8540_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_REVISION", "En revisión"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVA", "Correctiva"),
                            ("PREVENTIVA", "Preventiva"),
                            ("INSPECCION", "Inspección"),
                        ],
                        default="CORRECTIVA",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("EN_PROCESO", "En proceso"),
                            ("CERRADA", "Cerrada"),
                            ("PLANIFICADA", "Planificada"),
                        ],
                        default="ABIERTA",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("symptom", models.TextField(blank=True, default="")),
                ("cause", models.TextField(blank=True, default="")),
                ("action_taken", models.TextField(blank=True, default="")),
                ("downtime_hours", models.FloatField(blank=True, null=True)),
                ("repair_hours", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "issue",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order",
                        to="equipment.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("A", "Turno A"),
                            ("B", "Turno B"),
                            ("DIA", "Día"),
                            ("NOCHE", "Noche"),
                        ],
                        default="A",
                        max_length=10,
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("hourmeter_start", models.FloatField(blank=True, null=True)),
                ("hourmeter_end", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Operativo"),
                            ("DETENIDO", "Detenido"),
                            ("MANTENCION", "Mantención"),
                            ("STANDBY", "Standby"),
                        ],
                        default="OPERATIVO",
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_logs",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "equipment_id"],
                "indexes": [
                    models.Index(
                        fields=["equipment", "date"],
                        name="equipment_d_equipme_c268ad_idx",
                    ),
                    models.Index(
                        fields=["date", "shift"], name="equipment_d_date_00fb76_idx"
                    ),
                ],
                "unique_together": {("date", "equipment", "shift")},
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["equipment", "status"], name="equipment_i_equipme_f2f029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["reported_at"], name="equipment_i_reporte_630981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["equipment", "status"], name="equipment_w_equipme_c2cb2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["opened_at"], name="equipment_w_opened__9c89ef_idx"
            ),
        ),
    ]
