# Generated by Django 5.2.11 on 2026-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="entered_shop_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="returned_service_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
