# Generated by Django 5.2.11 on 2026-02-18 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_workorder_entered_shop_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["type", "status"], name="equipment_w_type_fdbe5e_idx"
            ),
        ),
    ]
